SELECT T.TABLE_TYPE, T.TABLE_SCHEMA + '.' + T.TABLE_NAME AS TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS C
INNER JOIN INFORMATION_SCHEMA.TABLES T 
    ON T.TABLE_CATALOG = C.TABLE_CATALOG 
        AND T.TABLE_SCHEMA = C.TABLE_SCHEMA
        AND T.TABLE_NAME = C.TABLE_NAME
WHERE COLUMN_NAME LIKE '%%'
ORDER BY 1, 2, 3

-- Use sp_help "<schema>.<table_name>" to show more thorough details about a table.
-- sp_help ""
