SELECT DB_NAME() [DATABASE_NAME]
, SCHEMA_NAME([SCHEMA_ID]) [SCHEMA_NAME]
, NAME [STORED_PROCEDURE_NAME]
, OBJECT_DEFINITION (OBJECT_ID) [TSQL_DEFINITION]
, create_date [CREATE_DATE]
, modify_date [MODIFY_DATE]
FROM SYS.PROCEDURES
WHERE TYPE_DESC = N'SQL_STORED_PROCEDURE'
    AND OBJECT_DEFINITION(OBJECT_ID) LIKE '%%'

--SELECT * FROM sys.procedures